# Generated by Django 6.0.6 on 2026-06-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
