# Generated by Django 6.0.6 on 2026-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to='teacherdp')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
